### ISSUE TITLE
[Bug]: Icon color

### ISSUE THREAD

**Issue by CanKolay3499** [HardcodedCat/termux-monet#25]
### Problem description

![Screenshot_20221026-181103_Pixel Launcher](https://user-images.githubusercontent.com/80613396/198064948-be9675d7-198a-41b0-9918-9f7ad0dae7f5.png)
Icon color is not the same as other apps

### Steps to reproduce the behavior.

Install termux monet and enable themed icons in android 13

### What is the expected behavior?

The icon should be same as the other apps

### System information

* Termux Monet version: the latest
* Is Nightly or Stable?: Nightly
* Android OS version: 13
* Device model: A217F

**Comment by HardcodedCat** [comment]
Could you please provide a screenshot of your paint chips? (you can activate this widget by doing A13 Easter egg in setttings, and then, place it on your home screen)

**Comment by CanKolay3499** [comment]
![Screenshot_20221027-135305_Pixel Launcher](https://user-images.githubusercontent.com/80613396/198266183-085f2bc5-fa8b-4ae0-bf6d-9b4f206eac78.png)

**Comment by HardcodedCat** [comment]
Thanks! i'll fix it. Soon you'll be able to test it on the latest nightly releases

**Comment by HardcodedCat** [comment]
Also, could you please check if the color matches the other icons in light mode?

**Comment by HardcodedCat** [comment]
Latest nightly build with this correction:
https://github.com/HardcodedCat/termux-monet/actions/runs/3341076215

**Comment by CanKolay3499** [comment]
The issue was fixed. Thanks
