### ISSUE TITLE
[Bug]: cursor blink rate can't be set to 0

### ISSUE THREAD

**Issue by fiplox** [HardcodedCat/termux-monet#32]
### Problem description

If cursor blink rate is set to 0, cursor still blinks, setting from 100 to 2000 works as expected.

### Steps to reproduce the behavior.

set `terminal-cursor-blink-rate = 0`

### What is the expected behavior?

cursor is not blinking

### System information

* Termux Monet version: 0.118.0-26
* Is Nightly or Stable?: stable
* Android OS version: 13
* Device model: samsung galaxy tab s7, xiaomi mi 11 lite NE
*

**Comment by HardcodedCat** [comment]
While i investigate this issue, add `echo -e '\e[2 q'` to your bashrc so that the cursor is set to steady mode everytime you open the terminal

**Comment by HardcodedCat** [comment]
It's fixed. For now, use the [Latest Nightly build](https://github.com/HardcodedCat/termux-monet/actions/runs/3808595532) until the fix gets included on a release
