### ISSUE TITLE
[Bug]: why is the toolbar not transparent when background image is enabled?

### ISSUE THREAD

**Issue by aicynide** [HardcodedCat/termux-monet#41]
### Problem description

Toolbar not transparent 

### Steps to reproduce the behavior.

Enable Background Image

### System information

* Termux Monet version: latest
* Is Nightly or Stable?: Stable
* Android OS version: 11
* Device model: Womsung
*

**Comment by HardcodedCat** [comment]
That's disabled for now

**Comment by aicynide** [comment]
@HardcodedCat how to enabls friend

**Comment by aicynide** [comment]
Hey please tell how to enable it 🙂

**Comment by HardcodedCat** [comment]
It's disabled on the code because of monet background

I'm planning to add a switch to enable transparency + blur, but i don't know java so.. it's complicated.

**Comment by aicynide** [comment]
You maintaining https://github.com/HardcodedCat/RealtimeBlurView_v2 I'm surprised you don't `public static voi main String args();`
