### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [HardcodedCat/termux-monet#50]
### Problem description

The stated translation licenses on Weblate GPLv3-only, Apache 2.0 and MIT, and I am thinking the current translations weren't taken under any of the latter licenses seeing as the main project license is GPLv3, and the main project is GPLv3-only.

### Steps to reproduce the behavior.

Displayed on https://hosted.weblate.org/projects/termux-monet/#information

### What is the expected behavior?

Can be changed in
https://hosted.weblate.org/settings/termux-monet/termux-shared/
and
https://hosted.weblate.org/settings/termux-monet/terminal-view/

### System information

N/A

**Comment by HardcodedCat** [comment]
Well, the translation licenses are just matching the respective library licenses.

Check https://github.com/HardcodedCat/termux-monet/blob/master/LICENSE-EXCEPTIONS.md
