### ISSUE TITLE
[Bug]: Crash: SystemVibratorManager cannot be cast to Vibrator

### ISSUE THREAD

**Issue by gutyina70** [HardcodedCat/termux-monet#65]
### Problem description

Termux monet crashes when the user triggers a vibration.

[termux-crash_report.log](https://github.com/HardcodedCat/termux-monet/files/11593452/termux-crash_report.log)

### Steps to reproduce the behavior.

1. Open termux monet
2. Press backspace to cause a vibration
3. Crash

### What is the expected behavior?

Termux monet shouldn't crash.

### System information

* Termux Monet version: 0.118.0
* Is Nightly or Stable?: Stable
* Android OS version: 12
* Device model: Galaxy A12

**Comment by agnostic-apollo** [comment]
Due to https://github.com/HardcodedCat/termux-monet/commit/f870e4bd898c40f2c3e439bdfa0fbb786fad309e

Ref termux/termux-app#3427
